export const AUTH_START = "AUTH_START";
export const DELETE_ACCOUNT_START = "DELETE_ACCOUNT_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
export const AUTH_TOKEN_SUCCESS = "AUTH_TOKEN_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const DELETE_ACCOUNT_FAIL = "DELETE_ACCOUNT_FAIL";
export const AUTH_SET_DISCOUNT_TEXT = "AUTH_SET_DISCOUNT_TEXT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_USER_ID = "SET_USER_ID";
export const TOKEN_SUCCESS = "TOKEN_SUCCESS";

export const VERIFY_USER_START = "VERIFY_USER_START";
export const VERIFY_USER_SUCCESS = "VERIFY_USER_SUCCESS";
export const VERIFY_USER_FAIL = "VERIFY_USER_FAIL";

export const MYPROFILE_SET_ACTIVE_INDEX = "MYPROFILE_SET_ACTIVE_INDEX";
export const USER_FINANCE_SET_ACTIVE_INDEX = "USER_FINANCE_SET_ACTIVE_INDEX";

export const ADD_TRIP_SUCCESS = "ADD_TRIP_SUCCESS";
export const ADD_TRIP_START = "ADD_TRIP_START";
export const ADD_TRIP_FAIL = "ADD_TRIP_FAIL";
export const ADD_TRIP_TOGGLE_CHECK = "ADD_TRIP_TOGGLE_CHECK";

export const ADD_BOOKING_SUCCESS = "ADD_BOOKING_SUCCESS";
export const ADD_BOOKING_START = "ADD_BOOKING_START";
export const ADD_BOOKING_FAIL = "ADD_BOOKING_FAIL";

export const SEARCH_TRIPS_FAIL = "SEARCH_TRIPS_FAIL";
export const SEARCH_TRIPS_START = "SEARCH_TRIPS_START";
export const SEARCH_TRIPS_SUCCESS = "SEARCH_TRIPS_SUCCESS";
export const SEARCH_TRIPS_SUCCESS_OVERRIDE = "SEARCH_TRIPS_SUCCESS_OVERRIDE";

export const SEARCH_BOOKINGS_FAIL = "SEARCH_BOOKINGS_FAIL";
export const SEARCH_BOOKINGS_START = "SEARCH_BOOKINGS_START";
export const SEARCH_BOOKINGS_SUCCESS = "SEARCH_BOOKINGS_SUCCESS";
export const SEARCH_BOOKINGS_SUCCESS_OVERRIDE = "SEARCH_BOOKINGS_SUCCESS_OVERRIDE";

export const SEARCH_BOOKINGS_PAGE_SET_INITIAL = "SEARCH_BOOKINGS_PAGE_SET_INITIAL";

export const SET_USER_INFO = "SET_USER_INFO";
export const CLEAR_USER_INFO = "CLEAR_USER_INFO";
export const TOGGLE_PROFILE_TYPE = "TOGGLE_PROFILE_TYPE";

export const GET_TRIPS_START = "GET_TRIPS_START";
export const GET_TRIPS_SUCCESS = "GET_TRIPS_SUCCESS";
export const GET_INITIAL_TRIPS_SUCCESS = "GET_INITIAL_TRIPS_SUCCESS";
export const GET_TRIPS_FAIL = "GET_TRIPS_FAIL";

export const GET_SENDER_NOTIFS_FAIL = "GET_SENDER_NOTIFS_FAIL";
export const GET_INITIAL_SENDER_NOTIFS_SUCCESS = "GET_INITIAL_SENDER_NOTIFS_SUCCESS";
export const GET_SENDER_NOTIFS_SUCCESS = "GET_SENDER_NOTIFS_SUCCESS";
export const GET_SENDER_NOTIFS_START = "GET_SENDER_NOTIFS_START";

export const GET_CARRIER_NOTIFS_FAIL = "GET_CARRIER_NOTIFS_FAIL";
export const GET_INITIAL_CARRIER_NOTIFS_SUCCESS = "GET_INITIAL_CARRIER_NOTIFS_SUCCESS";
export const GET_CARRIER_NOTIFS_SUCCESS = "GET_CARRIER_NOTIFS_SUCCESS";
export const GET_CARRIER_NOTIFS_START = "GET_CARRIER_NOTIFS_START";

export const GET_RESERVATIONS_START = "GET_RESERVATIONS_START";
export const GET_RESERVATIONS_SUCCESS = "GET_RESERVATIONS_SUCCESS";
export const GET_INITIAL_RESERVATIONS_SUCCESS = "GET_INITIAL_RESERVATIONS_SUCCESS";
export const GET_RESERVATIONS_FAIL = "GET_RESERVATIONS_FAIL";

export const GET_INCOMING_TRANSACTIONS_START = "GET_INCOMING_TRANSACTIONS_START";
export const GET_INCOMING_TRANSACTIONS_SUCCESS = "GET_INCOMING_TRANSACTIONS_SUCCESS";
export const GET_INITIAL_INCOMING_TRANSACTIONS_SUCCESS = "GET_INITIAL_INCOMING_TRANSACTIONS_SUCCESS";
export const GET_INCOMING_TRANSACTIONS_FAIL = "GET_INCOMING_TRANSACTIONS_FAIL";


export const GET_WITHDRAWAL_TRANSACTIONS_START = "GET_WITHDRAWAL_TRANSACTIONS_START";
export const GET_WITHDRAWAL_TRANSACTIONS_SUCCESS = "GET_WITHDRAWAL_TRANSACTIONS_SUCCESS";
export const GET_INITIAL_WITHDRAWAL_TRANSACTIONS_SUCCESS = "GET_INITIAL_WITHDRAWAL_TRANSACTIONS_SUCCESS";
export const GET_WITHDRAWAL_TRANSACTIONS_FAIL = "GET_WITHDRAWAL_TRANSACTIONS_FAIL";


export const GET_DEPOSIT_TRANSACTIONS_START = "GET_DEPOSIT_TRANSACTIONS_START";
export const GET_DEPOSIT_TRANSACTIONS_SUCCESS = "GET_DEPOSIT_TRANSACTIONS_SUCCESS";
export const GET_INITIAL_DEPOSIT_TRANSACTIONS_SUCCESS = "GET_INITIAL_DEPOSIT_TRANSACTIONS_SUCCESS";
export const GET_DEPOSIT_TRANSACTIONS_FAIL = "GET_DEPOSIT_TRANSACTIONS_FAIL";


export const GET_FAILED_TRANSACTIONS_START = "GET_FAILED_TRANSACTIONS_START";
export const GET_FAILED_TRANSACTIONS_SUCCESS = "GET_FAILED_TRANSACTIONS_SUCCESS";
export const GET_INITIAL_FAILED_TRANSACTIONS_SUCCESS = "GET_INITIAL_FAILED_TRANSACTIONS_SUCCESS";
export const GET_FAILED_TRANSACTIONS_FAIL = "GET_FAILED_TRANSACTIONS_FAIL";

export const GET_FUNDS_START = "GET_FUNDS_START";
export const GET_FUNDS_SUCCESS = "GET_FUNDS_SUCCESS";
export const GET_FUNDS_FAIL = "GET_FUNDS_FAIL";

export const GET_PAYMENT_METHODS_START = "GET_PAYMENT_METHODS_START";
export const GET_PAYMENT_METHODS_SUCCESS = "GET_PAYMENT_METHODS_SUCCESS";
export const GET_PAYMENT_METHODS_FAIL = "GET_PAYMENT_METHODS_FAIL";

export const GET_OUTGOING_TRANSACTIONS_START = "GET_OUTGOING_TRANSACTIONS_START";
export const GET_OUTGOING_TRANSACTIONS_SUCCESS = "GET_OUTGOING_TRANSACTIONS_SUCCESS";
export const GET_INITIAL_OUTGOING_TRANSACTIONS_SUCCESS = "GET_INITIAL_OUTGOING_TRANSACTIONS_SUCCESS";
export const GET_OUTGOING_TRANSACTIONS_FAIL = "GET_OUTGOING_TRANSACTIONS_FAIL";

export const GET_SELECTABLE_RESERVATIONS_START = "GET_SELECTABLE_RESERVATIONS_START";
export const GET_SELECTABLE_RESERVATIONS_SUCCESS = "GET_SELECTABLE_RESERVATIONS_SUCCESS";
export const GET_INITIAL_SELECTABLE_RESERVATIONS_SUCCESS = "GET_INITIAL_SELECTABLE_RESERVATIONS_SUCCESS";
export const GET_SELECTABLE_RESERVATIONS_FAIL = "GET_SELECTABLE_RESERVATIONS_FAIL";

export const GET_USER_BOOKINGS_START = "GET_USER_BOOKINGS_START";
export const GET_USER_BOOKINGS_SUCCESS = "GET_USER_BOOKINGS_SUCCESS";
export const GET_INITIAL_USER_BOOKINGS_SUCCESS = "GET_INITIAL_USER_BOOKINGS_SUCCESS";
export const GET_USER_BOOKINGS_FAIL = "GET_USER_BOOKINGS_FAIL";

export const GET_ALERTS_START = "GET_ALERTS_START";
export const GET_ALERTS_SUCCESS = "GET_ALERTS_SUCCESS";
export const GET_ALERTS_FAIL = "GET_ALERTS_FAIL";

export const SEND_PACKAGE_OPEN_MODAL = "SEND_PACKAGE_OPEN_MODAL";
export const SEND_PACKAGE_CLOSE_MODAL = "SEND_PACKAGE_CLOSE_MODAL";
export const SEND_PACKAGE_OPEN_MODAL_FOR_TRIP = "SEND_PACKAGE_OPEN_MODAL_FOR_TRIP";

export const SELECT_RESERVATIONS_OPEN_MODAL = "SELECT_RESERVATIONS_OPEN_MODAL";
export const SELECT_RESERVATIONS_CLOSE_MODAL = "SELECT_RESERVATIONS_CLOSE_MODAL";
export const SELECT_RESERVATIONS_OPEN_MODAL_FOR_TRIP = "SELECT_RESERVATIONS_OPEN_MODAL_FOR_TRIP";
export const MODAL_SELECT_RESERVATION = "MODAL_SELECT_RESERVATION";
export const SET_LANG = "SET_LANG";

export const SIGNUP_PARENT_OPEN_MODAL = "SIGNUP_PARENT_OPEN_MODAL";
export const SIGNUP_PARENT_CLOSE_MODAL = "SIGNUP_PARENT_CLOSE_MODAL";

export const PAYMENT_OPTIONS_OPEN_MODAL = "PAYMENT_OPTIONS_OPEN_MODAL";
export const PAYMENT_OPTIONS_CLOSE_MODAL = "PAYMENT_OPTIONS_CLOSE_MODAL";

export const SIGNUP_OPEN_MODAL = "SIGNUP_OPEN_MODAL";
export const SIGNUP_CLOSE_MODAL = "SIGNUP_CLOSE_MODAL";
export const SIGNUP_WITH_DISCOUNT_OPEN_MODAL = "SIGNUP_WITH_DISCOUNT_OPEN_MODAL";

export const LOGIN_PARENT_OPEN_MODAL = "LOGIN_PARENT_OPEN_MODAL";
export const LOGIN_PARENT_CLOSE_MODAL = "LOGIN_PARENT_CLOSE_MODAL";

export const SELECT_CREDIT_CARD_MODAL_OPEN_MODAL = "SELECT_CREDIT_CARD_MODAL_OPEN_MODAL";
export const SELECT_CREDIT_CARD_MODAL_CLOSE_MODAL = "SELECT_CREDIT_CARD_MODAL_CLOSE_MODAL";
export const SELECT_CREDIT_CARD_MODAL_GET_CARDS_START = "SELECT_CREDIT_CARD_MODAL_GET_CARDS_START";
export const SELECT_CREDIT_CARD_MODAL_GET_CARDS_SUCCESS = "SELECT_CREDIT_CARD_MODAL_GET_CARDS_SUCCESS";
export const SELECT_CREDIT_CARD_MODAL_GET_CARDS_FAIL = "SELECT_CREDIT_CARD_MODAL_GET_CARDS_FAIL";
export const SELECT_CREDIT_CARD_MODAL_SELECT_CARD = "SELECT_CREDIT_CARD_MODAL_SELECT_CARD";

export const LOGIN_OPEN_MODAL = "LOGIN_OPEN_MODAL";
export const LOGIN_CLOSE_MODAL = "LOGIN_CLOSE_MODAL";

export const FORGOT_PASSWORD_OPEN_MODAL = "FORGOT_PASSWORD_OPEN_MODAL";
export const FORGOT_PASSWORD_CLOSE_MODAL = "FORGOT_PASSWORD_CLOSE_MODAL";

export const UPDATE_TRIP_OPEN_MODAL = "UPDATE_TRIP_OPEN_MODAL";
export const UPDATE_TRIP_CLOSE_MODAL = "UPDATE_TRIP_CLOSE_MODAL";
export const UPDATE_TRIP_START = "UPDATE_TRIP_START";
export const UPDATE_TRIP_FAIL = "UPDATE_TRIP_FAIL";
export const UPDATE_TRIP_SUCCESS = "UPDATE_TRIP_SUCCESS";

export const UPDATE_BOOKING_OPEN_MODAL = "UPDATE_BOOKING_OPEN_MODAL";
export const UPDATE_BOOKING_CLOSE_MODAL = "UPDATE_BOOKING_CLOSE_MODAL";
export const UPDATE_BOOKING_START = "UPDATE_BOOKING_START";
export const UPDATE_BOOKING_FAIL = "UPDATE_BOOKING_FAIL";
export const UPDATE_BOOKING_SUCCESS = "UPDATE_BOOKING_SUCCESS";

export const DELETE_BOOKING_CONFIRM_SET_BOOKING = "DELETE_BOOKING_CONFIRM_SET_BOOKING";
export const DELETE_BOOKING_CONFIRM_CLOSE_MODAL = "DELETE_BOOKING_CONFIRM_CLOSE_MODAL";
export const DELETE_BOOKING_CONFIRM_OPEN_MODAL = "DELETE_BOOKING_CONFIRM_OPEN_MODAL";

export const DELETE_TRIP_CONFIRM_SET_TRIP = "DELETE_TRIP_CONFIRM_SET_TRIP";
export const DELETE_TRIP_CONFIRM_CLOSE_MODAL = "DELETE_TRIP_CONFIRM_CLOSE_MODAL";
export const DELETE_TRIP_CONFIRM_OPEN_MODAL = "DELETE_TRIP_CONFIRM_OPEN_MODAL";

export const DECLINE_BOOKING_SET_BOOKING = "DECLINE_BOOKING_SET_BOOKING";
export const DECLINE_BOOKING_CLOSE_MODAL = "DECLINE_BOOKING_CLOSE_MODAL";
export const DECLINE_BOOKING_OPEN_MODAL = "DECLINE_BOOKING_OPEN_MODAL";

export const CANCEL_BOOKING_SET_BOOKING = "CANCEL_BOOKING_SET_BOOKING";
export const CANCEL_BOOKING_CLOSE_MODAL = "CANCEL_BOOKING_CLOSE_MODAL";
export const CANCEL_BOOKING_OPEN_MODAL = "CANCEL_BOOKING_OPEN_MODAL";
export const CANCEL_BOOKING_SET_REFUND_AMOUNT = "CANCEL_BOOKING_SET_REFUND_AMOUNT";

export const DELETE_ACCOUNT_OPEN_MODAL = "DELETE_ACCOUNT_OPEN_MODAL";
export const DELETE_ACCOUNT_CLOSE_MODAL = "DELETE_ACCOUNT_CLOSE_MODAL";

export const VALIDATE_BOOKING_SET_BOOKING = "VALIDATE_BOOKING_SET_BOOKING";
export const VALIDATE_BOOKING_CLOSE_MODAL = "VALIDATE_BOOKING_CLOSE_MODAL";
export const VALIDATE_BOOKING_OPEN_MODAL = "VALIDATE_BOOKING_OPEN_MODAL";

export const PROPOSE_PRICE_ON_BOOKING_SET_ID = "PROPOSE_PRICE_ON_BOOKING_SET_ID";
export const PROPOSE_PRICE_ON_BOOKING_OPEN_MODAL = "PROPOSE_PRICE_ON_BOOKING_OPEN_MODAL";
export const PROPOSE_PRICE_ON_BOOKING_CLOSE_MODAL = "PROPOSE_PRICE_ON_BOOKING_CLOSE_MODAL";

export const CONFIRM_BOOKING_PRICE_SET_INFO = "CONFIRM_BOOKING_PRICE_SET_INFO";
export const CONFIRM_BOOKING_PRICE_OPEN_MODAL = "CONFIRM_BOOKING_PRICE_OPEN_MODAL";
export const CONFIRM_BOOKING_PRICE_CLOSE_MODAL = "CONFIRM_BOOKING_PRICE_CLOSE_MODAL";
export const CONFIRM_BOOKING_PRICE_SET_PRICE = "CONFIRM_BOOKING_PRICE_SET_PRICE";

export const PAYMENT_FORM_OPEN_MODAL = "PAYMENT_FORM_OPEN_MODAL";
export const PAYMENT_FORM_CLOSE_MODAL = "PAYMENT_FORM_CLOSE_MODAL";
export const PAYMENT_FORM_START_PAY = "PAYMENT_FORM_START_PAY";
export const PAYMENT_FORM_END_PAY = "PAYMENT_FORM_END_PAY";
export const SET_CARD_REGISTRATION_DATA = "SET_CARD_REGISTRATION_DATA";
export const SET_NATURAL_USER_ID = "SET_NATURAL_USER_ID";

export const BANK_ACCOUNT_FORM_OPEN_MODAL = "BANK_ACCOUNT_FORM_OPEN_MODAL";
export const BANK_ACCOUNT_FORM_CLOSE_MODAL = "BANK_ACCOUNT_FORM_CLOSE_MODAL";
export const BANK_ACCOUNT_FORM_GET_MAX_FUNDS_SUCCESS = "BANK_ACCOUNT_FORM_GET_MAX_FUNDS_SUCCESS";
export const BANK_ACCOUNT_FORM_GET_MAX_FUNDS_START = "BANK_ACCOUNT_FORM_GET_MAX_FUNDS_START";
export const BANK_ACCOUNT_FORM_GET_MAX_FUNDS_FAIL = "BANK_ACCOUNT_FORM_GET_MAX_FUNDS_FAIL";

export const BANK_ACCOUNT_FORM_GET_CASHOUT_START = "BANK_ACCOUNT_FORM_GET_CASHOUT_START";
export const BANK_ACCOUNT_FORM_GET_CASHOUT_SUCCESS = "BANK_ACCOUNT_FORM_GET_CASHOUT_SUCCESS";
export const BANK_ACCOUNT_FORM_GET_CASHOUT_FAIL = "BANK_ACCOUNT_FORM_GET_CASHOUT_FAIL";

export const ADD_TRIP_CLOSE_MODAL = "ADD_TRIP_CLOSE_MODAL";
export const ADD_TRIP_OPEN_MODAL = "ADD_TRIP_OPEN_MODAL";

export const COMPLETE_PROFILE_OPEN_MODAL = "COMPLETE_PROFILE_OPEN_MODAL";
export const COMPLETE_PROFILE_CLOSE_MODAL = "COMPLETE_PROFILE_CLOSE_MODAL";

export const PRODUCT_DELIVERY_MODAL_OPEN_MODAL = "PRODUCT_DELIVERY_MODAL_OPEN_MODAL";
export const PRODUCT_DELIVERY_MODAL_CLOSE_MODAL = "PRODUCT_DELIVERY_MODAL_CLOSE_MODAL";

export const VERIFY_EMAIL_CLOSE_MODAL = "VERIFY_EMAIL_CLOSE_MODAL";
export const VERIFY_EMAIL_OPEN_MODAL = "VERIFY_EMAIL_OPEN_MODAL";