export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_TOKEN_SUCCESS = "AUTH_TOKEN_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_SET_DISCOUNT_TEXT = "AUTH_SET_DISCOUNT_TEXT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_USER_ID = "SET_USER_ID";
export const TOKEN_SUCCESS = "TOKEN_SUCCESS";


export const MYPROFILE_SET_ACTIVE_INDEX = "MYPROFILE_SET_ACTIVE_INDEX";

export const ADD_TRIP_SUCCESS = "ADD_TRIP_SUCCESS";
export const ADD_TRIP_START = "ADD_TRIP_START";
export const ADD_TRIP_FAIL = "ADD_TRIP_FAIL";

export const ADD_BOOKING_SUCCESS = "ADD_BOOKING_SUCCESS";
export const ADD_BOOKING_START = "ADD_BOOKING_START";
export const ADD_BOOKING_FAIL = "ADD_BOOKING_FAIL";

export const SEARCH_TRIPS_FAIL = "SEARCH_TRIPS_FAIL";
export const SEARCH_TRIPS_START = "SEARCH_TRIPS_START";
export const SEARCH_TRIPS_SUCCESS = "SEARCH_TRIPS_SUCCESS";
export const SEARCH_TRIPS_SUCCESS_OVERRIDE = "SEARCH_TRIPS_SUCCESS_OVERRIDE";

export const SEARCH_BOOKINGS_FAIL = "SEARCH_BOOKINGS_FAIL";
export const SEARCH_BOOKINGS_START = "SEARCH_BOOKINGS_START";
export const SEARCH_BOOKINGS_SUCCESS = "SEARCH_BOOKINGS_SUCCESS";
export const SEARCH_BOOKINGS_SUCCESS_OVERRIDE = "SEARCH_BOOKINGS_SUCCESS_OVERRIDE";

export const SET_USER_INFO = "SET_USER_INFO";
export const CLEAR_USER_INFO = "CLEAR_USER_INFO";


export const GET_TRIPS_START = "GET_TRIPS_START";
export const GET_TRIPS_SUCCESS = "GET_TRIPS_SUCCESS";
export const GET_TRIPS_FAIL = "GET_TRIPS_FAIL";

export const GET_RESERVATIONS_START = "GET_RESERVATIONS_START";
export const GET_RESERVATIONS_SUCCESS = "GET_RESERVATIONS_SUCCESS";
export const GET_RESERVATIONS_FAIL = "GET_RESERVATIONS_FAIL";

export const SEND_PACKAGE_OPEN_MODAL = "SEND_PACKAGE_OPEN_MODAL";
export const SEND_PACKAGE_CLOSE_MODAL = "SEND_PACKAGE_CLOSE_MODAL";
export const SEND_PACKAGE_OPEN_MODAL_FOR_TRIP = "SEND_PACKAGE_OPEN_MODAL_FOR_TRIP";

export const SET_LANG = "SET_LANG";
