# Generated by Django 2.2 on 2020-11-13 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_by_sender', models.BooleanField(default=False)),
                ('made_on', models.DateField(blank=True, null=True)),
                ('collector_id', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('arrival_date', models.DateField()),
                ('weight', models.CharField(choices=[('500g', '0.1 - 500g'), ('1kg', '500g - 1kg'), ('5kg', '1.1kg - 5kg'), ('10kg', '5.1kg - 10kg'), ('20kg', '10.1kg - 20kg'), ('30kg', '20.1kg - 30kg'), ('40kg', '30.1kg - 40kg'), ('huge', '40.1kg +')], max_length=50)),
                ('space', models.CharField(choices=[('xxs', 'Extra Extra Small'), ('xs', 'Extra small'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large'), ('xxl', 'Extra Extra Large'), ('xxl', 'Extra Extra Extra Large')], max_length=50)),
                ('price', models.CharField(choices=[('low', 'Low value'), ('mid', 'Medium value'), ('high', 'High value'), ('lux', 'Luxury items'), ('exc', 'Exclusive')], max_length=50)),
                ('product_category', models.CharField(choices=[('food', 'Food'), ('elec', 'Electronics'), ('dress', 'Dresses'), ('shoe', 'Shoes'), ('doc', 'Documents'), ('uts', 'Kitchen utensils'), ('app', 'Electrical appliances'), ('skin', 'Skin care'), ('jel', 'Jewelry'), ('misc', 'Miscellaneous')], max_length=50)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('recipient_name', models.CharField(max_length=250)),
                ('recipient_phone_number', models.CharField(max_length=250)),
                ('proposed_price', models.CharField(max_length=250)),
                ('terms_conditions', models.BooleanField(default=False)),
                ('user_agreement', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.Product')),
            ],
        ),
    ]
