# Generated by Django 2.2 on 2021-01-14 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
        ('booking', '0001_initial'),
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='product',
            name='departure_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.City'),
        ),
        migrations.AddField(
            model_name='product',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.City'),
        ),
        migrations.AddField(
            model_name='priceproposal',
            name='booking_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='booking.BookingRequest'),
        ),
        migrations.AddField(
            model_name='priceproposal',
            name='request_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='notif',
            name='booking_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='booking.BookingRequest'),
        ),
        migrations.AddField(
            model_name='notif',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='notif',
            name='price_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='booking.PriceProposal'),
        ),
        migrations.AddField(
            model_name='notif',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='trip.Trip'),
        ),
        migrations.AddField(
            model_name='codes',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='booking.BookingRequest'),
        ),
        migrations.AddField(
            model_name='codes',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='trip.Trip'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='booking.Product'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='request_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='trip.Trip'),
        ),
    ]
