# Generated by Django 2.2 on 2020-11-05 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
        ('booking', '0001_initial'),
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='product',
            name='departure_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.Location'),
        ),
        migrations.AddField(
            model_name='product',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.Location'),
        ),
        migrations.AddField(
            model_name='product',
            name='pickup_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.Location'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.Weight'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='booking.Product'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='request_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='trip.Trip'),
        ),
    ]
