# Generated by Django 2.2 on 2020-10-14 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('userprofile', '0001_initial'),
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='request_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='trip.Trip'),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='booking',
            name='departure_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.Location'),
        ),
        migrations.AddField(
            model_name='booking',
            name='destination_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.Location'),
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.Price'),
        ),
        migrations.AddField(
            model_name='booking',
            name='space_booked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.Space'),
        ),
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='trip.Trip'),
        ),
        migrations.AddField(
            model_name='booking',
            name='weight_booked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.Weight'),
        ),
    ]
