# Generated by Django 2.2 on 2020-11-19 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20201115_1938'),
        ('trip', '0002_auto_20201113_1755'),
        ('booking', '0002_auto_20201113_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('cre', 'Created'), ('rec', 'Offers recieved'), ('con', 'Offer confirmed'), ('awa', 'Awaiting collection'), ('col', 'Collected'), ('del', 'Delivered')], default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Notif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unseen', 'Unseen'), ('seen', 'Seen')], max_length=50)),
                ('type', models.CharField(choices=[('offer_rec', 'Offer recieved'), ('trip_booked', 'Trip Booked'), ('offer_conf', 'Offer confirmed')], max_length=50)),
                ('booking_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='booking.BookingRequest')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.UserProfile')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='trip.Trip')),
            ],
        ),
    ]
