# Generated by Django 2.2 on 2020-10-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20201029_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='made_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='arrival_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='creation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='departure_date',
            field=models.DateField(),
        ),
    ]
