# Generated by Django 2.2 on 2020-11-23 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20201123_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='departure_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.City'),
        ),
        migrations.AlterField(
            model_name='product',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.City'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pickup_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.City'),
        ),
    ]
