# Generated by Django 2.2 on 2022-01-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210116_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount_paid',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='charges_paid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='proposed_price',
            field=models.FloatField(default=0),
        ),
    ]
