# Generated by Django 2.2 on 2021-01-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210116_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='proposed_price',
            field=models.IntegerField(default=0),
        ),
    ]
