# Generated by Django 2.2 on 2020-11-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20201105_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(choices=[('low', 'Low value'), ('mid', 'Medium value'), ('high', 'High value'), ('lux', 'Luxury items'), ('exc', 'Exclusive')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('food', 'Food'), ('elec', 'Electronics'), ('dress', 'Dresses'), ('shoe', 'Shoes'), ('doc', 'Documents'), ('uts', 'Kitchen utensils'), ('app', 'Electrical appliances'), ('skin', 'Skin care'), ('jel', 'Jewelry'), ('misc', 'Miscellaneous')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(choices=[('500g', '0.1 - 500g'), ('1kg', '500g - 1kg'), ('5kg', '1.1kg - 5kg'), ('10kg', '5.1kg - 10kg'), ('20kg', '10.1kg - 20kg'), ('30kg', '20.1kg - 30kg'), ('40kg', '30.1kg - 40kg'), ('huge', '40.1kg +')], max_length=50),
        ),
    ]
