# Generated by Django 2.2 on 2021-01-09 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20201226_0147'),
        ('booking', '0002_auto_20201226_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent_to_sender', 'Sent to sender'), ('validated_by_carrier', 'Validated by carrier'), ('obsolete', 'Obsolete')], max_length=50)),
                ('code', models.CharField(max_length=250, unique=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='booking.BookingRequest')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='trip.Trip')),
            ],
        ),
    ]
