# Generated by Django 2.2 on 2021-01-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='validated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codes',
            name='validation_attempts',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
