# Generated by Django 2.2 on 2020-11-20 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20201115_1938'),
        ('booking', '0003_auto_20201119_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=50)),
                ('request_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.UserProfile')),
            ],
        ),
    ]
