# Generated by Django 2.2 on 2021-11-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20210126_1704'),
        ('booking', '0003_auto_20210123_2014'),
    ]

    operations = [
    ]
