# Generated by Django 2.2 on 2020-10-31 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20201029_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='trip',
        ),
        migrations.AddField(
            model_name='product',
            name='terms_conditions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='user_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='collector_id',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='made_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='trip.Trip'),
        ),
        migrations.AlterField(
            model_name='product',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
