# Generated by Django 2.2 on 2020-11-23 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20201123_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pickup_location',
        ),
    ]
