# Generated by Django 2.2 on 2020-10-31 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20201031_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.Location'),
        ),
    ]
