# Generated by Django 2.2 on 2020-11-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_product_pickup_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('cre', 'Created'), ('rec', 'Offers recieved'), ('boo', 'Booked'), ('con', 'Offer confirmed'), ('awa', 'Awaiting collection'), ('col', 'Collected'), ('del', 'Delivered')], max_length=50),
        ),
    ]
