# Generated by Django 2.2 on 2020-11-20 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_priceproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceproposal',
            name='booking_request',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='booking.BookingRequest'),
            preserve_default=False,
        ),
    ]
