# Generated by Django 2.2 on 2021-01-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20210109_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='validation_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
