# Generated by Django 2.2 on 2021-11-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_merge_20211130_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='proposed_price',
            field=models.FloatField(default=0),
        ),
    ]
