# Generated by Django 2.2 on 2020-12-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20201130_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='type',
            field=models.CharField(choices=[('offer_rec', 'Offer recieved'), ('trip_booked', 'Trip Booked'), ('offer_conf', 'Offer confirmed'), ('request_validated', 'Booking request validated'), ('request_declined', 'Booking request declined'), ('payment_for_booking', 'You have paid for your booking')], max_length=50),
        ),
    ]
