# Generated by Django 2.2 on 2021-01-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20210109_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='type',
            field=models.CharField(choices=[('offer_rec', 'Offer recieved'), ('trip_booked', 'Trip Booked'), ('offer_conf', 'Offer confirmed'), ('request_validated', 'Booking request validated'), ('request_declined', 'Booking request declined'), ('request_cancelled', 'Booking request cancelled'), ('payment_for_booking', 'You have paid for your booking'), ('delivered', 'Product delivered')], max_length=50),
        ),
    ]
