# Generated by Django 2.2 on 2020-11-20 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_priceproposal_booking_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif',
            name='price_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='booking.PriceProposal'),
        ),
        migrations.AlterField(
            model_name='notif',
            name='booking_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='booking.BookingRequest'),
        ),
    ]
