# Generated by Django 2.2 on 2020-12-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20201212_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='space',
            field=models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(choices=[('500g', '0.1 - 500g'), ('1kg', '500g - 1kg'), ('5kg', '1.1kg - 5kg'), ('10kg', '5.1kg - 10kg'), ('20kg', '10.1kg - 20kg'), ('30kg', '20.1kg - 30kg')], max_length=50),
        ),
    ]
