# Generated by Django 2.2 on 2020-12-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20201213_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
