# Generated by Django 2.2 on 2020-11-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20201031_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='space',
            field=models.CharField(choices=[('xxs', 'Extra Extra Small'), ('xs', 'Extra small'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large'), ('xxl', 'Extra Extra Large'), ('xxl', 'Extra Extra Extra Large')], max_length=50),
        ),
    ]
