# Generated by Django 2.2 on 2022-03-10 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PercentagePromo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('percentage', models.IntegerField(default=0)),
                ('max_usage_count', models.IntegerField(default=0)),
                ('usage_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('discount', models.CharField(max_length=15)),
                ('max_usage_count', models.IntegerField(default=1)),
                ('usage_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keep_me_logged_in', models.BooleanField(default=True)),
                ('can_take_parcel', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('units', models.CharField(default='kg', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(blank=True, default=0, max_length=250, null=True)),
                ('pay_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_number', models.CharField(blank=True, default='000000', max_length=50, null=True)),
                ('country', models.CharField(blank=True, default='FR', max_length=50, null=True)),
                ('user_type', models.CharField(blank=True, choices=[('sender', 'Sender'), ('carrier', 'Carrier')], max_length=100, null=True)),
                ('sex', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=100, null=True)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='uploads/id_documents/')),
                ('profile_pic', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='uploads/profile_images/')),
                ('terms_conditions', models.BooleanField(default=False)),
                ('nat_user_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('wallet_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.UserSettings')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('percentage_promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.PercentagePromo')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.PromoCode')),
                ('userprofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.UserProfile')),
            ],
        ),
    ]
