# Generated by Django 2.2 on 2020-10-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('Sender', 'Sender'), ('Carrier', 'Carrier')], max_length=50),
        ),
    ]
