# Generated by Django 2.2 on 2021-01-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('sender', 'Sender'), ('carrier', 'Carrier')], max_length=50, null=True),
        ),
    ]
