# Generated by Django 2.2 on 2020-11-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20201128_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='passport_number',
            field=models.CharField(blank=True, default='000000', max_length=50, null=True),
        ),
    ]
