# Generated by Django 2.2 on 2020-10-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20201014_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='terms_conditions',
            field=models.BooleanField(default=False),
        ),
    ]
