# Generated by Django 2.2 on 2020-10-31 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20201029_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='amount',
            field=models.CharField(max_length=50),
        ),
    ]
