# Generated by Django 2.2 on 2020-12-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20201130_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wallet_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
