# Generated by Django 2.2 on 2020-10-15 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userprofile_terms_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='userprofile.UserSettings'),
        ),
    ]
