# Generated by Django 2.2 on 2021-01-11 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20210102_1353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='ParcelType',
        ),
        migrations.DeleteModel(
            name='Space',
        ),
    ]
