"""
Django settings for inzula project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['INZ_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
MANUAL_DEBUG = False

ALLOWED_HOSTS = ['dkx1b8wlo613w.cloudfront.net', 'inzula.app', 'www.inzula.app', '15.237.97.243']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.twitter',
    'allauth.socialaccount.providers.google',
    'corsheaders',
    'rest_auth',
    'rest_auth.registration',
    'rest_framework',
    'rest_framework.authtoken',
    'trip',
    'booking',
    'userprofile',
    'pay_process',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'corsheaders.middleware.CorsPostCsrfMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'inzula.urls'

PROD_TEMP_DIRS = [
    os.path.join(BASE_DIR, 'build'),
    os.path.join(BASE_DIR, 'public')
    ]

PROD_STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'public'),
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'build'),
    os.path.join(BASE_DIR, 'build', 'static')
    ]

DEBUG_STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'public'),
    os.path.join(BASE_DIR, 'static'),
    ]

DEBUG_TEMP_DIRS = [
    os.path.join(BASE_DIR, 'public'),
    ]

DEBUG_STATIC_ROOT = None
PROD_STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = DEBUG_STATICFILES_DIRS if MANUAL_DEBUG else PROD_STATICFILES_DIRS
TEMP_DIRS = DEBUG_TEMP_DIRS if MANUAL_DEBUG else PROD_TEMP_DIRS


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': TEMP_DIRS,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inzula.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ['INZ_DB_NAME'],
        'USER': os.environ['INZ_DB_USER'],
        'PASSWORD': os.environ['INZ_DB_PASSWORD'],
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.BrowsableAPIRenderer',
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.TemplateHTMLRenderer',
        'rest_framework.renderers.MultiPartRenderer',
        'rest_framework.renderers.HTMLFormRenderer'
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser'
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 10
}


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
STATIC_ROOT = DEBUG_STATIC_ROOT if MANUAL_DEBUG else PROD_STATIC_ROOT
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
SITE_ID = 1
REST_USE_JWT = True

# Account parameters
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'username'
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

# CORS parameters
CORS_ALLOW_ALL_ORIGINS = True

# Email parameters
EMAIL_HOST_URL = 'https://inzula.app/verify/'
DEFAULT_FROM_EMAIL = os.getenv("DEFAULTFROMEMAIL", 'inzula.app@gmail.com')
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'inzula.app@gmail.com'
EMAIL_HOST_PASSWORD = os.environ['INZ_EMAIL_HOST_PASSWORD']

# SSO parameters
GOOGLE_CLIENT_ID = os.environ['INZ_GOOGLE_CLIENT_ID']
GOOGLE_CLIENT_SECRET = os.environ['INZ_GOOGLE_CLIENT_SECRET']
FACEBOOK_APP_ID = os.environ['INZ_FACEBOOK_APP_ID']
FACEBOOK_APP_SECRET = os.environ['INZ_FACEBOOK_APP_SECRET']

# Twilio config
TWILIO_ACCOUNT_SID = os.environ['INZ_TWILIO_ACCOUNT_SID']
TWILIO_AUTH_TOKEN = os.environ['INZ_TWILIO_AUTH_TOKEN']
PHONE_NUMBER = os.environ['INZ_TWILIO_PHONE_NUMBER']

# Delivery code config
MAX_VALIDATION_ATTEMPTS = 5

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = False if MANUAL_DEBUG else True

INZULA_EMAIL = "inzula.app@gmail.com"

# deployment
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False

if DEBUG == False:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True