export const msg = {
  'gen.loading': "Loading",
  'layout.discount': "15% discount",
  'layout.dispatch': "Dispatch",
  'layout.transport': "Transport",
  'layout.login': "Login",
  'layout.signup': "Sign up",
  'layout.profile': "Profile",
  'layout.booking': "Reservation",
  'layout.trips': "Trips",
  'layout.messages': "Messaging",
  'layout.alerts': "Alerts",
  'layout.finances': "Finances",
  'layout.logout': "Logout",
  'home_text_video.send_parcels': "Send parcels to your loved ones, via contacts in your network",
  'home_text_video.inzula_use': "INZULA connects travelers with kgs available and people in their network wanting to ship at low cost",
  'home_text_video.ship_now': "Ship items now",
  'home_text_video.earn_money': "Earn money while travelling",
  'add_trip_form.earn_money': "Earn money every time you travel.",
  'add_trip_form.deliver_parcels': "Deliver parcels to individuals wishing to ship at low prices and amortize your travel costs.",
  'add_trip_form.how_it_works': "How does it work?",
  'add_trip_form.add_trip': "Add information about your trip to earn money.",
  'add_trip_form.please_login': "Please login to add a new trip",
  'add_trip_form.cb_date': "Come back Date",
  'add_trip_form.dep_date': "Departure Date",
  'add_trip_form.one_way': "One way",
  'add_trip_form.round_trip': "Round trip",
  'add_trip_form.add_your_trip': "Add your trip",
  'booking_card.description': "Description",
  'booking_card.arrival_date': "Arrival date",
  'booking_card.departure_loc': "Departure location",
  'booking_card.pickup_loc': "Pickup location",
  'footer.who_we_are': "Who we are",
  'footer.how_it_works': "How it works",
  'footer.faqs': "Frequently asked questions",
  'footer.contact': "Contact us",
  'footer.insurance': "Insurance",
  'footer.legal': "Legal information",
  'footer.trans': "Transparency",
  'footer.rights': "All rights reserved",
  'footer.terms': "Terms and Conditions",
  'footer.privacy_policy': "Privacy Policy",
  'how_inzula_works.send': "Send packages to loved ones all over the world inexpensively through people in your network. This saves you up to 70% of the price you would have paid using a traditional parcel delivery service. The bonus? Your packages are insured and you have the choice of carrier.",
  'how_inzula_works.ship': "For Shippers",
  'how_inzula_works.tell_pkg': "1 - Tell us more about your package",
  'how_inzula_works.tell_pkg_desc': "With INZULA, you can ship your packages anywhere in the world. To get started, create your profile and fill in as much information as possible about the package you want.hate to ship, that is to say the nature of the package to be shipped, the place where you want to ship your package, information on the recipient of the package, the desired date of dispatch. An estimate of the cost of transporting the package will be offered to you on the platform.",
  'how_inzula_works.wait_carr': "2- Wait for carriers to make offers to you",
  'how_inzula_works.wait_carr_desc': "Once you have published your offer, we will share it with our community. Travelers interested in this destination will contact you to make offers of parcel transport.",
  'how_inzula_works.reward_carr': "3 - Agree on a reward amount with the traveler",
  'how_inzula_works.reward_carr_desc': "INZULA will automatically calculate all charges applicable to the transport of the package, including: - the amount agreed with the carrier - the insurance costs of your package - platform management fees If for any reason the traveler cancels their trip, you will receive a full refund.",
  'how_inzula_works.meet_carr': "4- Agree on a place to meet the traveler",
  'how_inzula_works.meet_carr_desc': "Once the transaction is settled, agree on a time and a public place to deliver your package to the traveler. During the delivery of the package, remember: - to take a picture of yourself with the carrier to certify the delivery of the package to the latter - to verify the identity document of the person to whom youhand over the package - confirm delivery of the package to the traveler",
  'how_inzula_works.fund_trip': "Fund your trip every time you travel with INZULA. Our travelers usually deliver a handful of packages and write off their plane ticket. Not only will you make money traveling, but you will meet amazing people along the way.",
  'how_inzula_works.carry': "For Carriers",
  'how_inzula_works.find_request': "1 - Find a shipment request and make a transport proposal",
  'how_inzula_works.find_request_desc': "Find a shipment request that matches your next trip. Make an offer and set your Traveler Reward - the amount your buyer will pay you for the delivery of their item.",
  'how_inzula_works.place': "2- Agree on a place to meet the sender",
  'how_inzula_works.place_desc': "Once yourth proposition validated, uUse the INZULA courier to arrange a location to pick up the package. During the delivery of the package, remember: - to take a picture of yourself with the sender to certify that the package has been delivered to you - to check the identity document of the person who gives you the parcel.",
  'how_inzula_works.sender': "3 - Meet the recipient of the package where you are going",
  'how_inzula_works.sender_desc': "Once at destination, you have 3 days from your arrival in the country to contact the recipient of the package. Arrange an appointment in a public place to deliver the package to the recipient and remember to take a photo of yourself with the latter to certify the delivery.",
  'how_inzula_works.pay': "4- Receive your payment",
  'how_inzula_works.pay_desc': "Once the package has been delivered, validate the discount on the site. The sender then has 2 days to confirm the delivery by hand to the recipient, and you will then receive your payment.",
  'how_inzula_works.title': "How Inzula works",
  'home_service.title': "We are proud to offer these services",
  'home_service.customer_service': "CUSTOMER SERVICE AT YOUR DISPOSAL",
  'home_service.customer_service_desc': "Quickly and easily find a car-pooling nearby among those proposed destinations",
  'home_service.pay_methods': "VARIOUS PAYMENT METHODS",
  'home_service.pay_methods_desc': "To make your life easier, we accept various payment methods including Visa, MasterCard, Orange Money, other options to come",
  'home_service.eco': "ECONOMIC",
  'home_service.eco_desc': "Send your parcels anywhere in the world, at a much cheaper price than those offered on the market",
  'home_service.user_comm': "VERIFIED USER COMMUNITY",
  'home_service.user_comm_desc': "INZULA is more than a platform, it is a community. We know each of our members. How? 'Or' What ? We check profiles, reviews, IDs and theft. So you know who you're talking to",
  'home_service.security': "SECURITY",
  'home_service.security_desc': "Protection insurance for your goods is offered to you based on the declared value of the goods you want to ship",
  'home_service.customer_support': "CUSTOMER SERVICE AT YOUR DISPOSAL",
  'home_service.customer_support_desc': "Our customer service is at your disposal to respond to your problems that may arise during transactions.",
  'login.title': "Log-in to your account",
  'login.username': "Username",
  'login.password': "Password",
  'login.login_btn': "Login",
  'login.new': "New to Inzula?",
  'login_parent.username': "Sign in with Facebook",
  'login_parent.password': "Sign in with Gmail",
  'login_parent.login': "Use email address",
  'login_parent.not_yet_signed_up': "Not yet a member?",
  'my_profile.msg': "You are in {profileType} mode. Switch?",
  'profile_tab.membership': "Member since: {date_joined}",
  'profile_tab.phone': "Phone number {phone_number}",
  'profile_tab.email': "Email {email}",
  'profile_tab.passport': "Passport number {passport_number}",
  'profile_tab.upload_imgs': "Choose profile image",
  'profile_tab.perso_info': "Personal information",
  'profile_tab.f_name': "First name",
  'profile_tab.l_name': "Last name",
  'profile_tab.p_number': "Phone number",
  'profile_tab.e_mail': "Email",
  'profile_tab.country': "Country",
  'profile_tab.p_number': "Passport number",
  'search_requests.title': "Prefer to know what shipping offers are available before committing?",
  'search_requests.head': "No worries, you can add the country of departure and destination of your trip and thus access the requests for available expeditions.",
  'search_requests.departure': "Departure",
  'search_requests.destination': "Destination",
  'search_requests.travel_date': "Travel Date",
  'search_requests.search': "Search",
  'search_requests.price': "Price {p1} - {p2}",
  'search_requests.weight': "Weight {p1} - {p2}",
  'search_requests.p_size': "Product size",
  'search_requests.p_category': "Product category",
  'search_trips.title': "Prefer to know what shipping offers are available before committing?",
  'search_trips.h2': "No worries, you can add the country of departure and destination of your trip and thus access the requests for available expeditions.",
  'search_trips.cant_find_trip': "  Can't find a trip?",
  'search_trips.click_book_request': "click here to save a booking request",
  'search_trips.get_contacted': "so you can be later contacted by travellers.",
  'search_trips.departure': "Departure",
  'search_trips.destination': "Destination",
  'search_trips.travel_date': "Travel date",
  'add_booking.notif_success': "Your request has been added",
  'add_booking.p_details': "Product details",
  'add_booking.p_details': "Enter product and recipient's details",
  'add_booking.confirm': "Confirm",
  'add_booking.confirm_request': "Confirm your request",
  'add_booking.choose_p_images': "Choose product images",
  'add_booking.p_name': "Product name:",
  'add_booking.p_location': "Product location:",
  'add_booking.delivery_date': "Delivery date:",
  'add_booking.p_category': "Product category:",
  'add_booking.p_size': "Product size:",
  'add_booking.proposed_price': "Proposed price:",
  'add_booking._rec_name': "Recipient name:",
  'add_booking.rec_phone_number': "Recipient phone number:",
  'add_booking.pickup_address': "Pickup address:",
  'add_booking.weight': "Weight:",
  'add_booking.p_value': "Product value:",
  'add_booking.p_desc': "Product description:",
  'add_booking.rec_name_field': "Recipient name",
  'add_booking.phone_number_field': "Recipient phone number",
  'add_booking.p_name_field': "Product name",
  'add_booking.p_location_field': "Product location",
  'add_booking.delivery_date_field': "Delivery Date",
  'add_booking.pickup_address_field': "Pickup address",
  'add_booking.p_category_field': "Product category",
  'add_booking.p_weight_field': "Product weight",
  'add_booking.p_size_field': "Product size",
  'add_booking.p_value_field': "Product value",
  'add_booking.proposed_price_field': "Proposed price",
  'add_booking.rec_name_field': "Reciever's name",
  'add_booking.rec_phone_number_field': "Reciever's phone number",
  'add_booking.p_description_field': "Short description of the product",
  'add_booking.terms_check': "I have read and accept the terms and conditions",
  'add_booking.user_agreement_check': "I agree to the user agreement",
  'add_booking.back': "Back",
  'add_booking.next': "Next",
  'add_booking.confirm_request': "Confirm request",
  'add_booking_modal.add_request': "Add a booking request",
  'add_booking_modal.cancel': "Cancel",
  'signup.title': "Signup to Inzula",
  'signup.f_name': "First name",
  'signup.l_name': "Last name",
  'signup.username': "Username",
  'signup.email': "E-mail address",
  'signup.passport': "Password",
  'signup.confirm_password': "Confirm password",
  'signup.agree_terms': "I agree to the Terms and Conditions",
  'signup.signup': "Signup",
  'signup.have_account': "Already have an account?",
  'signup.login': "Login",
  'signup.use_fb': "Sign up with Facebook",
  'signup.use_gmail': "Sign up with Gmail",
  'signup.use_email': "Use email address",
  'signup_discount.title': "Signup now to benefit from a 5% discount for each of your first three parcel epeditions.",
  'transport_title.services_title': "We are proud to offer these services",
  'transport_title.add_trip': "ADD YOUR TRIP",
  'transport_title.make_offer': "MAKE TRANSPORT OFFERS",
  'transport_title.meet_sender': "MEETING WITH THE SENDER - COLLECT THE PACKAGE",
  'transport_title.deliver': "DELIVER THE PACKAGE AND GET PAID",
  'trip_card.username': "User name: ",
  'trip_card.comeback_date': "Comeback date: ",
  'trip_card.depart_date': "Depart date: ",
  'trip_card.departure_location': "Departure: ",
  'trip_card.destination_location': "Destination: ",
};
