export const msg = {
  'gen.loading': "Loading...",
  'layout.discount': "15% discount",
  'layout.dispatch': "Dispatch",
  'layout.transport': "Transport",
  'layout.login': "Login",
  'layout.signup': "Sign up",
  'layout.profile': "Profile",
  'layout.booking': "Reservation",
  'layout.trips': "Trips",
  'layout.messages': "Messaging",
  'layout.alerts': "Alerts",
  'layout.finances': "Finances",
  'layout.logout': "Logout",
  'home_text_video.send_parcels': "Send parcels to your loved ones, via contacts in your network",
  'home_text_video.inzula_use': "INZULA connects travelers with kgs available and people in their network wanting to ship at low cost",
  'home_text_video.ship_now': "Ship items now",
  'home_text_video.earn_money': "Earn money while travelling",
  'add_trip_form.earn_money': "Earn money every time you travel.",
  'add_trip_form.deliver_parcels': "Deliver parcels to individuals wishing to ship at low prices and amortize your travel costs.",
  'add_trip_form.how_it_works': "How does it work?",
  'add_trip_form.add_trip': "Add information about your trip to earn money.",
  'add_trip_form.please_login': "Please login to add a new trip",
  'add_trip_form.cb_date': "Come back Date",
  'add_trip_form.dep_date': "Departure Date",
  'add_trip_form.one_way': "One way",
  'add_trip_form.round_trip': "Round trip",
  'add_trip_form.add_your_trip': "Add your trip",
  'add_trip_form.dest_location': "Destination location",
  'add_trip_form.depart_location': "Departure location",
  'add_trip_form.trip': "Trip",
  'booking_card.description': "Description: ",
  'booking_card.arrival_date': "Arrival date: ",
  'booking_card.departure_loc': "Departure location: ",
  'booking_card.pickup_loc': "Pickup location: ",
  'booking_card.weight': "Weight: ",
  'booking_card.size': "Size:",
  'booking_card.category': "Category:",
  'booking_card.value': "Value:",
  'booking_card.price': "Price: ",
  'booking_card.validate': "Validate",
  'booking_card.decline': "Decline",
  'booking_card.username': "Username",
  'booking_card.recipient_phone_number': "Recipient phone #:",
  'booking_card.recipient_name': "Recipient name:",
  'footer.who_we_are': "Who we are",
  'footer.how_it_works': "How it works",
  'footer.blog': "Blog",
  'footer.faqs': "Frequently asked questions",
  'footer.contact': "Contact us",
  'footer.insurance': "Insurance",
  'footer.legal': "Legal information",
  'footer.trans': "Transparency",
  'footer.rights': "All rights reserved",
  'footer.terms': "Terms and Conditions",
  'footer.privacy_policy': "Privacy Policy",
  'how_inzula_works.send': "Send packages to loved ones all over the world inexpensively through people in your network. This saves you up to 70% of the price you would have paid using a traditional parcel delivery service. The bonus? Your packages are insured and you have the choice of carrier.",
  'how_inzula_works.ship': "For Shippers",
  'how_inzula_works.tell_pkg': "1 - Tell us more about your package",
  'how_inzula_works.tell_pkg_desc': "With INZULA, you can ship your packages anywhere in the world. To get started, create your profile and fill in as much information as possible about the package you want.hate to ship, that is to say the nature of the package to be shipped, the place where you want to ship your package, information on the recipient of the package, the desired date of dispatch. An estimate of the cost of transporting the package will be offered to you on the platform.",
  'how_inzula_works.wait_carr': "2- Wait for carriers to make offers to you",
  'how_inzula_works.wait_carr_desc': "Once you have published your offer, we will share it with our community. Travelers interested in this destination will contact you to make offers of parcel transport.",
  'how_inzula_works.reward_carr': "3 - Agree on a reward amount with the traveler",
  'how_inzula_works.reward_carr_desc': "INZULA will automatically calculate all charges applicable to the transport of the package, including: - the amount agreed with the carrier - the insurance costs of your package - platform management fees If for any reason the traveler cancels their trip, you will receive a full refund.",
  'how_inzula_works.meet_carr': "4- Agree on a place to meet the traveler",
  'how_inzula_works.meet_carr_desc': "Once the transaction is settled, agree on a time and a public place to deliver your package to the traveler. During the delivery of the package, remember: - to take a picture of yourself with the carrier to certify the delivery of the package to the latter - to verify the identity document of the person to whom youhand over the package - confirm delivery of the package to the traveler",
  'how_inzula_works.fund_trip': "Fund your trip every time you travel with INZULA. Our travelers usually deliver a handful of packages and write off their plane ticket. Not only will you make money traveling, but you will meet amazing people along the way.",
  'how_inzula_works.carry': "For Carriers",
  'how_inzula_works.find_request': "1 - Find a shipment request and make a transport proposal",
  'how_inzula_works.find_request_desc': "Find a shipment request that matches your next trip. Make an offer and set your Traveler Reward - the amount your buyer will pay you for the delivery of their item.",
  'how_inzula_works.place': "2- Agree on a place to meet the sender",
  'how_inzula_works.place_desc': "Once yourth proposition validated, uUse the INZULA courier to arrange a location to pick up the package. During the delivery of the package, remember: - to take a picture of yourself with the sender to certify that the package has been delivered to you - to check the identity document of the person who gives you the parcel.",
  'how_inzula_works.sender': "3 - Meet the recipient of the package where you are going",
  'how_inzula_works.sender_desc': "Once at destination, you have 3 days from your arrival in the country to contact the recipient of the package. Arrange an appointment in a public place to deliver the package to the recipient and remember to take a photo of yourself with the latter to certify the delivery.",
  'how_inzula_works.pay': "4- Receive your payment",
  'how_inzula_works.pay_desc': "Once the package has been delivered, validate the discount on the site. The sender then has 2 days to confirm the delivery by hand to the recipient, and you will then receive your payment.",
  'how_inzula_works.title': "How Inzula works",
  'home_service.title': "We are proud to offer these services",
  'home_service.customer_service': "CUSTOMER SERVICE AT YOUR DISPOSAL",
  'home_service.customer_service_desc': "Quickly and easily find a car-pooling nearby among those proposed destinations",
  'home_service.pay_methods': "VARIOUS PAYMENT METHODS",
  'home_service.pay_methods_desc': "To make your life easier, we accept various payment methods including Visa, MasterCard, Orange Money, other options to come",
  'home_service.eco': "ECONOMIC",
  'home_service.eco_desc': "Send your parcels anywhere in the world, at a much cheaper price than those offered on the market",
  'home_service.user_comm': "VERIFIED USER COMMUNITY",
  'home_service.user_comm_desc': "INZULA is more than a platform, it is a community. We know each of our members. How? 'Or' What ? We check profiles, reviews, IDs and theft. So you know who you're talking to",
  'home_service.security': "SECURITY",
  'home_service.security_desc': "Protection insurance for your goods is offered to you based on the declared value of the goods you want to ship",
  'home_service.customer_support': "CUSTOMER SERVICE AT YOUR DISPOSAL",
  'home_service.customer_support_desc': "Our customer service is at your disposal to respond to your problems that may arise during transactions.",
  'login.title': "Log-in to your account",
  'login.username': "Username",
  'login.password': "Password",
  'login.login_btn': "Login",
  'login.signup_btn': "Sign up",
  'login.cancel': "Cancel",
  'login.new': "New to Inzula?",
  'login_parent.use_facebook': "Sign in with Facebook",
  'login_parent.use_gmail': "Sign in with Gmail",
  'login_parent.use_username': "Use username",
  'login_parent.signup_btn': "Sign up",
  'login_parent.cancel': "Cancel",
  'login_parent.sign_in': "Sign in",
  'login_parent.not_yet_signed_up': "Not yet a member?",
  'my_profile.msg': "You are in {profileType} mode. Switch?",
  'profile_tab.membership': "Member since: {date_joined}",
  'profile_tab.phone': "Phone number {phone_number}",
  'profile_tab.email': "Email {email}",
  'profile_tab.sex': "Sex",
  'profile_tab.passport': "Passport number {passport_number}",
  'profile_tab.upload_imgs': "Choose profile image",
  'profile_tab.perso_info': "Personal information",
  'profile_tab.f_name': "First name",
  'profile_tab.l_name': "Last name",
  'profile_tab.phone_number': "Phone number",
  'profile_tab.e_mail': "Email",
  'profile_tab.country': "Country",
  'profile_tab.passport_number': "Passport number",
  'profile_tab.delete_account': "Delete my account.",
  'search_requests.title': "Prefer to know what shipping offers are available before committing?",
  'search_requests.head': "No worries, you can add the country of departure and destination of your trip and thus access the requests for available expeditions.",
  'search_requests.departure': "Departure",
  'search_requests.destination': "Destination",
  'search_requests.travel_date': "Travel Date",
  'search_requests.search': "Search",
  'search_requests.price': "Price",
  'search_requests.weight': "Weight",
  'search_requests.p_size': "Product size",
  'search_requests.p_category': "Product category",
  'search_trips.title': "Prefer to know what shipping offers are available before committing?",
  'search_trips.h2': "No worries, you can add the country of departure and destination of your trip and thus access the requests for available expeditions.",
  'search_trips.cant_find_trip': "  Can't find a trip? Click",
  'search_trips.click_book_request': " here ",
  'search_trips.get_contacted': " to save a parcel so you can be later contacted by travellers.",
  'search_trips.departure': "Departure",
  'search_trips.destination': "Destination",
  'search_trips.travel_date': "Travel date",
  'search_trips.search_btn': "Search",
  'search_trips.no_results': "No search results. Please try a more general search",
  'add_booking.notif_success': "Your request has been added",
  'add_booking.p_details': "Product details",
  'add_booking.p_r_details': "Enter product and recipient's details",
  'add_booking.confirm': "Confirm",
  'add_booking.confirm_request': "Confirm your request",
  'add_booking.choose_p_images': "Choose product images",
  'add_booking.pickup_loc_field': "Pickup location",
  'add_booking.p_name': "Product name:",
  'add_booking.p_location': "Product location:",
  'add_booking.delivery_date': "Delivery date:",
  'add_booking.p_category': "Product category:",
  'add_booking.p_size': "Product size:",
  'add_booking.proposed_price': "Proposed price:",
  'add_booking._rec_name': "Recipient name:",
  'add_booking.rec_phone_number': "Recipient phone number:",
  'add_booking.pickup_address': "Pickup address:",
  'add_booking.weight': "Weight:",
  'add_booking.p_value': "Product value:",
  'add_booking.p_desc': "Product description:",
  'add_booking.rec_name_field': "Recipient name",
  'add_booking.phone_number_field': "Recipient phone number",
  'add_booking.p_name_field': "Product name",
  'add_booking.p_location_field': "Product location",
  'add_booking.delivery_date_field': "Delivery Date",
  'add_booking.pickup_address_field': "Pickup address",
  'add_booking.p_category_field': "Product category",
  'add_booking.p_weight_field': "Product weight",
  'add_booking.p_size_field': "Product size",
  'add_booking.cancel': "Cancel",
  'add_booking.p_value_field': "Product value",
  'add_booking.proposed_price_field': "Proposed price",
  'add_booking.min_price_field': "Minimum price to propose",
  'add_booking.rec_phone_number_field': "Reciever's phone number",
  'add_booking.p_description_field': "Short description of the product",
  'add_booking.terms_check': "I have read and accept the terms and conditions",
  'add_booking.user_agreement_check': "I agree to the user agreement",
  'add_booking.back': "Back",
  'add_booking.next': "Next",
  'add_booking_modal.add_request': "Add a booking request",
  'add_booking_modal.cancel': "Cancel",
  'signup.title': "Signup to Inzula",
  'signup.f_name': "First name",
  'signup.l_name': "Last name",
  'signup.username': "Username",
  'signup.email': "E-mail address",
  'signup.password': "Password",
  'signup.confirm_password': "Confirm password",
  'signup.agree_terms': "I agree to the Terms and Conditions",
  'signup.signup': "Signup",
  'signup.have_account': "Already have an account?",
  'signup.login': "Login",
  'signup.use_fb': "Sign up with Facebook",
  'signup.use_gmail': "Sign up with Gmail",
  'signup.use_email': "Use username",
  'signup.cancel': "Cancel",
  'signup_discount.title': "Signup now to benefit from a 5% discount for each of your first three parcel epeditions.",
  'transport_title.services_title': "We are proud to offer these services",
  'transport_title.add_trip': "ADD YOUR TRIP",
  'transport_title.make_offer': "MAKE TRANSPORT OFFERS",
  'transport_title.meet_sender': "MEETING WITH THE SENDER - COLLECT THE PACKAGE",
  'transport_title.deliver': "DELIVER THE PACKAGE AND GET PAID",
  'trip_card.username': "User name: ",
  'trip_card.comeback_date': "Comeback date: ",
  'trip_card.depart_date': "Depart date: ",
  'trip_card.departure_location': "Departure: ",
  'trip_card.destination_location': "Destination: ",
  'notif_card.trip_booked': "Your trip has been booked.",
  'notif_card.offer_rec': "You have recieved an offer for this request.",
  'notif_card.request_validated': "Your booking request has been validated by the carrier.",
  'notif_card.request_declined': "Your booking request has been declined by the carrier: {username}.",
  'notif_card.product_delivered': "Your product has been delivered.",
  'notif_card.date': "Departure Date: ",
  'notif_card.created_on': "On: ",
  'notif_card.product': "Product: ",
  'notif_card.offer_price': "Price: ",
  'notif_card.trip': "Trip: ",
  'notif_card.mark_seen': "Mark as seen",
  'notif_card.payment_for_booking': "Payment for booking",
  'notif_card.request_cancelled': "You have cancelled this request.",
  'notif_card.payment_for_delivery': "You have received a payment for the delivery you made.",
  'profile_tab.personal_information': "Personal information",
  'profile_tab.first_name': "First name",
  'profile_tab.last_name': "Last name",
  'profile_tab.phone_number': "Phone number",
  'profile_tab.email': "Email",
  'profile_tab.phone_number_disp': "Phone number:",
  'profile_tab.email_disp': "Email:",
  'profile_tab.passport_number_disp': "Passport number:",
  'profile_tab.member_since': "Member since",
  'profile_tab.country': "Country",
  'profile_tab.save': "Save",
  'profile_tab.choose_profile_image': "Choose profile image",
  'user_bookings.no_bookings': "You have not recieved any bookings on your trips.",
  'user_bookings.loading': "Loading...",
  'user_reservations.loading': "Loading...",
  'user_reservations.no_reservations': "You have not created any reservations",
  'user_trips.loading': "Loading...",
  'user_trips.no_trips': "You have not created any trips",
  'carrier_notifs.loading': "Loading...",
  'carrier_notifs.no_notifs': "You have no notifications",
  'sender_notifs.loading': "Loading...",
  'sender_notifs.no_notifs': "You have no notifications",
  'verify_email.title': "Verifying your email...",
  'verify_email.success': "Email has been verified successfully",
  'verify_email.failed': "Failed to verify your email address.",
  'delete_account.title': "Delete your account.",
  'delete_account.question': "Are you sure you want to delete your account?",
  'delete_account.no': "No",
  'delete_account.yes': "Yes, delete my account.",
  'send_package.login_msg': "Please login to create a booking request.",
  'add_trip.login_msg': "Please login to add a new trip.",
  'user_transactions.no_transactions': "You have not made any transactions yet",
  'user_transactions.loading': "Loading...",
  'incoming_user_transactions.no_transactions': "You do not have any incoming transactions yet.",
  'outgoing_user_transactions.no_transactions': "You have not made any transactions yet.",
  'failed_user_transactions.no_transactions': "You do not have any failed transactions.",
  'transaction_card.payin': "Transaction: ",
  'transaction_card.creation_date': "Created on: ",
  'transaction_card.debited_funds': "Amount : ",
  'validate_booking.title': "Validate booking",
  'validate_booking.question':"Are you sure you want to validate this booking?",
  'validate_booking.no': "No",
  'validate_booking.yes': "Yes",
  'update_trip.title': "Update Trip",
  'update_trip.trip': "Trip",
  'update_trip.departure_date': "Departure date",
  'update_trip.return_date': "Return date",
  'update_trip.btn_title': "Update your trip",
  'update_trip.cancel': "Cancel",
  'update_booking.title': "Update Booking",
  'trip_card.book': "Book",
  'trip_card.username': "Username: ",
  'trip_card.depart_date': "Depart date: ",
  'trip_card.comeback_date': "Comeback date: ",
  'trip_card.departure': "Departure: ",
  'trip_card.destination': "Destination: ",
  'signup_discount.username': "Use username",
  'select_reservations.title': "Select bookings for this trip",
  'select_reservations.add_booking': "Add a booking",
  'select_reservations.book_with_selected': "Book with these reservations",
  'select_reservations.cancel': "Cancel",
  'select_credit_card.title': "Select credit card",
  'select_credit_card.pay_with_new': "Pay with new card",
  'select_credit_card.pay': "Pay",
  'select_credit_card.cancel': "Cancel",
  'search_requests.no_results': "No search results. Please try a more general search",
  'signup.default_profile_type': "Default profile type",
  'user_reservations.add_booking': "Add a booking",
  'user_trips.add_trip': "Add a trip",
  'complete_profile_modal.cancel': "Cancel",
  'complete_profile_modal.title': "Update your profile",
  'my_funds.cashable': "Amount available for withdrawal:",
  'my_funds.cashout': "Cash out",
  'my_funds.fraction_cashable': "You can only cash out part of this amount, depending on your pending transactions.",
  'my_funds.total_deposited': "Total of funds in your wallet: ",
  'paymentmethodcard.credit_card': "Credit card",
  'paymentmethodcard.paypal': "Paypal",
  'paymentmethodcard.wallet': "Wallet funds",
  'notif_card.created_by': "By: ",
  'booking_card.product_delivered': "Product delivered.",
  'booking_card.cancel_booking': "Cancel",
  'propose_price.title': "Propose price on booking",
  'propose_price.sub_title': "Enter the amount you propose to carry this product",
  'propose_price.propose_price': "Propose price (euros)",
  'propose_price.cancel': "Cancel",
  'product_delivery.title': "We have to ascertain that you have given the parcel to the recipient",
  'product_delivery.enter_code': "Enter the code recieved from the recipient.",
  'product_delivery.submit_code': "Submit this code.",
  'product_delivery.cancel': "Cancel",

  'search_trips.departure_location': "departure location",
  'search_trips.destination_location': "Destination location",

  'confirm_booking.title': "Confirm price",
  'confirm_booking.msg': "You are about to pay {price} euros and fees of {fees} euros to book this trip for your product.",
  'confirm_booking.confirm': "Confirm",
  'confirm_booking.decline': "Decline",

  'pay_choices.title': "Choice of Payment method",
  'pay_choices.select': "Select your method of payment.",
  'pay_choices.cancel': "Cancel",

  'my_profile.sender': "Switch to sender mode.",
  'my_profile.carrier': "Switch to carrier mode.",
  'creditcard_card.creation_date': "Added on: ",
  'login.forgot_password': "Forgot password ?",

  'payment_form.title': "Payment",
  'payment_form.price_msg': "You are about to pay {price} euros.",
  'payment_form.card_f_name': "Card holder first name(s)",
  'payment_form.card_l_name': "Card holder last name(s)",
  'payment_form.card_number': "Card number",
  'payment_form.exp_date_mm': "MM(expiration)",
  'payment_form.exp_date_yy': "YY",
  'payment_form.cvc': "CVC",
  'payment_form.pay': "Pay",
  'payment_form.cancel': "Cancel",
  'add_booking.add_request': "Add a booking request",
  'my_funds.no_cards': "You do not have any cards.",

  'cashout_form.title': "Enter bank account to which you want to cash out",
  'cashout_form.max_amt': "Maximum Amount you can cash out",
  'cashout_form.amt': "Amount",
  'cashout_form.account_owner_name': "Account holder name(s)",
  'cashout_form.account_owner_address': "Account holder address",
  'cashout_form.account_owner_postal_code': "Postal code",
  'cashout_form.country': "Country",
  'cashout_form.account_BIC': "BIC",
  'cashout_form.account_IBAN': "IBAN",
  'cashout_form.cashout': "Cash out",
  'cashout_form.cancel': "Cancel",

  'decline_booking.title': "Decline booking",
  'decline_booking.msg': "Are you sure you want to decline this booking?",
  'decline_booking.no': "No",
  'decline_booking.yes': "Yes",

  'cancel_booking.title': "Cancel booking",
  'cancel_booking.msg': "Are you sure you want to cancel this booking?",
  'cancel_booking.no': "No",
  'cancel_booking.yes': "Yes",

  'confirm_cancel_modal.msg': "If you confirm the cancellation of this booking, you will be refunded {amount} EUR",
  'complete_profile_modal.msg': "See my profile",

  'verify_email_confirm.title': "Verification email sent to your inbox",
  'verify_email_confirm.yes': "Ok",
  'verify_email_confirm.msg': "Please click on the link you have received by email. If you don't receive it soon enough, check your SPAM messages.",

  'delete_trip.title': "Delete trip",
  'delete_trip.msg': "Are you sure you want to delete this trip?",
  'delete_trip.no': "No",
  'delete_trip.yes': "Yes",

  'delete_booking.title': "Delete booking",
  'delete_booking.msg': "Are you sure you want to delete this booking?",
  'delete_booking.no': "No",
  'delete_booking.yes': "Yes",

  'profile_tab.username_': "Username: ",
  'profile_tab.fullname_': "Name: ",
  'profile_tab.file_size_error': "File is too big",
  'profile_tab.file_type_error': "File type not accepted",
  'profile_tab.passport_proof': "Passport document",
  'profile_tab.passport_upload_btn': "Click to upload passport document",

};
