export const msg = {
  myMessage: "Aujourd'hui, c'est le {ts, date, ::yyyyMMdd}",
  'layout.discount': "Remise de 15%",
  'layout.dispatch': "Expedier",
  'layout.transport': "Transporter",
  'layout.login': "Connexion",
  'layout.signup': "Inscription",
  'layout.profile': "Profil",
  'layout.booking': "Reservation",
  'layout.messages': "Messagerie",
  'layout.alerts': "Notifications",
  'layout.finances': "Finances",
  'layout.logout': "Deconnexion",
  'home_text_video.send_parcels': "Envoyez des colis a vos etres chers, via des contacts dans votre reseau",
  'home_text_video.inzula_use': "INZULA connecte des voyageurs detenant de l'espace dans leurs baggages avec des expediteurs dans leur reseau a moindre cout",
  'home_text_video.ship_now': "Expediez des articles ",
  'home_text_video.earn_money': "Gagnez de l'argent durant vos voyages",
};
