export const msg = {
  myMessage: "Aujourd'hui, c'est le {ts, date, ::yyyyMMdd}",
  'layout.discount': "Remise de 15%",
  'layout.dispatch': "Expédier",
  'layout.transport': "Transporter",
  'layout.login': "Connexion",
  'layout.signup': "Inscription",
  'layout.profile': "Profil",
  'layout.booking': "Réservation",
  'layout.trips': "Voyages",
  'layout.messages': "Messagerie",
  'layout.alerts': "Notifications",
  'layout.finances': "Finances",
  'layout.logout': "Déconnexion",
  'home_text_video.send_parcels': "Expédiez des colis à vos proches, via des contacts de votre réseau",
  'home_text_video.inzula_use': "INZULA connecte des voyageurs ayant des kgs disponibles et des personnes de leur réseau souhaitant expédier à bas coût",
  'home_text_video.ship_now': "Expediez des articles ",
  'home_text_video.earn_money': "Gagnez de l'argent durant vos voyages",
  'gen.loading': "Chargement",
  'add_trip_form.earn_money': "Gagnez de l’argent à chaque fois que vous voyagez.",
  'add_trip_form.deliver_parcels': "Livrez les colis de particuliers souhaitant expédier à bas prix et amortissez vos frais de voyages.",
  'add_trip_form.how_it_works': "Comment ça marche ?",
  'add_trip_form.add_trip': "Ajoutez les informations sur votre voyage pour gagner de l’argent.",
  'add_trip_form.please_login': "Veuillez vous connecter pour ajouter un nouveau voyage",
  'add_trip_form.cb_date': "Date de retour",
  'add_trip_form.dep_date': "Date de depart",
  'add_trip_form.one_way': "Aller",
  'add_trip_form.round_trip': "Aller-Retour",
  'add_trip_form.add_your_trip': "Ajoutez votre trajet",
  'booking_card.description': "Description",
  'booking_card.arrival_date': "Date d'arrivée",
  'booking_card.departure_loc': "Lieu de départ",
  'booking_card.pickup_loc': "Lieu de livraison du colis",
  'footer.who_we_are': "Qui nous sommes",
  'footer.how_it_works': "Comment ça marche ?",
  'footer.faqs': "Questions fréquentes",
  'footer.contact': "Contact",
  'footer.insurance': "Insurance",
  'footer.legal': "Informations légales",
  'footer.trans': "Transparence de la plateforme",
  'footer.rights': "Tous les droits sont réservés",
  'footer.terms': "Termes et Conditions",
  'footer.privacy_policy': "Politique de confidentialité",
  'how_inzula_works.send': "Envoyez des colis à vos proches partout dans le monde à bas prix via des  personnes  appartenant  à  votre  réseau.  Vous  économisez  ainsi jusqu’à  70%  du  prix  que  vous  auriez  payé  en  passant  par  un  service classique de livraison de colis. Le bonus ? Vos colis sont assurés et vous avez le choix du transporteur.",
  'how_inzula_works.ship': "Pour les expéditeurs",
  'how_inzula_works.tell_pkg': "1 - Dites nous en plus sur votre colis",
  'how_inzula_works.tell_pkg_desc': "Avec  INZULA,  vous  pouvez  expédier  vos  colis  partout  dans  le monde.  Pour  commencer,  créez  votre  profil  et  renseignez  le maximum d’informations sur le colis que vous souhaitez expédier, c’est-à-dire la nature du colis à expédier, le lieu où vous souhaitez expédier votre colis, les informations sur le destinataire du colis, la date souhaitée d’envoi d’expédition. Une estimation du coût du transport du colis vous sera proposée sur la plateforme.",
  'how_inzula_works.wait_carr': "2- Attendez que des transporteurs vous fassent des offres",
  'how_inzula_works.wait_carr_desc': "Une fois que vous aurez publié votre offre, nous là partagerons avec  notre  communauté.  Les  voyageurs  intéressés  par  cette destination  prendront  contact  avec  vous  pour  vous  faire  des offres de transport de colis.",
  'how_inzula_works.reward_carr': "3 - Convenez d’un montant de récompense avec le voyageur",
  'how_inzula_works.reward_carr_desc': "INZULA calculera automatiquement tous les frais applicables au transport du colis, en incluant: -  le montant convenu avec le transporteur -  les frais d’assurance de votre colis -  les frais de gestion de la plateformeSi pour une quelconque raison, le voyageur annule son voyage, vous recevrez un remboursement intégral.",
  'how_inzula_works.meet_carr': "4- Convenez d’un lieu pour rencontrer le voyageur",
  'how_inzula_works.meet_carr_desc': "Une fois la transaction réglée, convenez d’une heure et d’un lieu public pour remettre votre colis au voyageur. Durant la remise du colis, pensez bien : -  à vous prendre en photo avec le transporteur pour attester de la remise du colis à ce dernier  - à vérifier la pièce d’identité de celui à qui vous remettez le colis - confirmer la remise du colis au voyageur.",
  'how_inzula_works.fund_trip': "Subventionnez  votre  voyage  à  chaque  fois  que  vous  voyagez  avec INZULA.  Nos  voyageurs  livrent  généralement  une  poignée  de  colis  et amortissent ainsi leur billet d’avion. Non seulement vous gagnerez de l'argent  en  voyageant,  mais  vous  rencontrerez  des  personnes incroyables en cours de route.",
  'how_inzula_works.carry': "Pour les transporteurs",
  'how_inzula_works.find_request': "1 - Trouvez une demande d’expédition et faites une proposition de transport",
  'how_inzula_works.find_request_desc': "Recherchez  une  demande  d’expédition  qui  corresponde  à  votre prochain trajet. Faites une offre et définissez votre récompense de voyageur - le montant que votre acheteur vous paiera pour la livraison de son article.",
  'how_inzula_works.place': "2- Convenez d’un lieu pour rencontrer l’expéditeur ",
  'how_inzula_works.place_desc': "Une fois votre proposition validée, utilisez la messagerie d’INZULA pour convenir d’un lieu pour récupérer le colis.Durant la remise du colis, pensez bien : -  à vous prendre en photo avec l’expéditeur pour attester que le colis vous a été remis - à vérifier la pièce d’identité de celui qui vous remet le colis.",
  'how_inzula_works.sender': "3 - Rencontrez le destinataire du colis là où vous allez",
  'how_inzula_works.sender_desc': "Une fois à destination, vous disposez de 3 jours à compter de votre arrivée dans le pays pour contacter le destinataire du colis. Convenez d’un rdv dans un endroit public pour remettre le colis au destinataire et pensez à vous prendre en photo avec ce dernier pour attester de la remise.",
  'how_inzula_works.pay': "4- Recevez votre paiement",
  'how_inzula_works.pay_desc': "Une fois le colis remis, validez la remise sur le site. L’expéditeur dispose alors de 2 jours de délai pour confirmer la remise en main propre au destinataire, et vous recevrez alors votre paiement.",
  'how_inzula_works.title': "Comment INZULA fonctionne",
  'home_service.title': "Nous sommes fiers de vous proposer ce service",
  'home_service.customer_service': "Pratique",
  'home_service.customer_service_desc': "Trouvez  rapidement  et  facilement  un covalisage  à  proximité  parmi  celles destinations proposées",
  'home_service.pay_methods': "Avec divers moyens de paiement",
  'home_service.pay_methods_desc': "Afin de vous faciliter la vie, nous acceptons divers moyens de paiements incluant Visa, MasterCard, Orange Money, d’autres options à venir",
  'home_service.eco': "Economique",
  'home_service.eco_desc': "Envoyez vos colis partout dans le monde, à un prix  beaucoup  moins  onéreux  que  ceux proposés sur le marché",
  'home_service.user_comm': "Communauté d’utilisateurs vérifiés",
  'home_service.user_comm_desc': "INZULA c’est plus qu’une plateforme, c’est une communauté. Nous connaissons chacun de nos membres. Comment? Nous vérifions profils,  avis,  pièces  d’identité  et  vol. Vous savez ainsi avec qui vous échangez",
  'home_service.security': "Sécurité ",
  'home_service.security_desc': "Une assurance protection de vos biens vous est  proposé  en  fonction  de  la  valeur déclarative  des  biens  que  vous  souhaitez expédier",
  'home_service.customer_support': "Un service client à votre disposition",
  'home_service.customer_support_desc': "Notre  service  client  à  votre  disposition pour répondre à vos problématiques qui pourraient    survenir        durant    les transactions.",
  'login.title': "Connectez-vous à votre compte",
  'login.username': "Nom",
  'login.password': "Mot de passe",
  'login.login_btn': "Connexion",
  'login.new': "Nouveau sur Inzula ?",
  'login_parent.username': "Connexion avec Facebook",
  'login_parent.password': "Connexion avec Gmail",
  'login_parent.login': "Utiliser votre addresse email",
  'login_parent.not_yet_signed_up': "Vous n'avez pas de compte ?",
  'my_profile.msg': "En mode {profileType}. Changer?",
  'profile_tab.membership': "Membre depuis: {date_joined}",
  'profile_tab.phone': "Téléphone {phone_number}",
  'profile_tab.email': "Email {email}",
  'profile_tab.passport': "Numéro de Passeport {passport_number}",
  'profile_tab.upload_imgs': "Ajouter votre photo",
  'profile_tab.perso_info': "Informations personnelles",
  'profile_tab.f_name': "Prénom",
  'profile_tab.l_name': "Nom",
  'profile_tab.p_number': "Téléphone",
  'profile_tab.e_mail': "Email",
  'profile_tab.country': "Pays de résidence",
  'profile_tab.p_number': "Numéro de Passeport",
  'search_requests.title': "Vous préférez savoir quelles sont les offres d’expéditions disponibles avant de vous engager ?",
  'search_requests.head': "Pas de soucis, vous pouvez ajouter le pays de départ et de destination de votre trajet et ainsi accéder aux demandes d’expéditions disponibles.",
  'search_requests.departure': "Départ",
  'search_requests.destination': "Arrivée",
  'search_requests.travel_date': "Date du voyage",
  'search_requests.search': "Rechercher",
  'search_requests.price': "Prix {p1} - {p2}",
  'search_requests.weight': "Poids {p1} - {p2}",
  'search_requests.p_size': "Taille du colis",
  'search_requests.p_category': "Catégorie du colis",
  'search_trips.title': "Vous préférez savoir quelles sont les offres d’expéditions disponibles avant de vous engager ?",
  'search_trips.h2': "Pas de soucis, vous pouvez ajouter le pays de départ et de destination de votre trajet et ainsi accéder aux demandes d’expéditions disponibles.",
  'search_trips.cant_find_trip': "Impossible de trouver un voyage?",
  'search_trips.click_book_request': "cliquez ici pour enregistrer une demande de réservation",
  'search_trips.get_contacted': "afin que vous puissiez être contacté plus tard par les voyageurs.",
  'search_trips.departure': "Départ",
  'search_trips.destination': "Arrivée",
  'search_trips.travel_date': "Date du voyage",
  'add_booking.notif_success': "Votre demande a été ajoutée",
  'add_booking.p_details': "Détails du colis",
  'add_booking.p_details': "Entrez les détails du colis et du destinataire",
  'add_booking.confirm': "Confirmez",
  'add_booking.confirm_request': "Confirmez votre demande",
  'add_booking.choose_p_images': "Choisissez les images du colis",
  'add_booking.p_name': "Nom du colis:",
  'add_booking.p_location': "Où se trouve le colis:",
  'add_booking.delivery_date': "Date limite de livraison du colis:",
  'add_booking.p_category': "Catégorie du colis:",
  'add_booking.p_size': "Taille:",
  'add_booking.proposed_price': "Prix:",
  'add_booking._rec_name': "Prénom et Nom du destinataire final:",
  'add_booking.rec_phone_number': "Numéro de téléphone du destinataire final:",
  'add_booking.pickup_address': "Adresse de livraison du colis:",
  'add_booking.weight': "Poids:",
  'add_booking.p_value': "Valeur déclarative du colis:",
  'add_booking.p_desc': "Description du colis:",
  'add_booking.rec_name_field': "Prénom et Nom du destinataire final",
  'add_booking.phone_number_field': "Numéro de téléphone du destinataire final",
  'add_booking.p_name_field': "Product name",
  'add_booking.p_location_field': "Où se trouve le colis ?",
  'add_booking.delivery_date_field': "Date limite de livraison du colis",
  'add_booking.pickup_address_field': "Lieu de retrait du colis",
  'add_booking.p_category_field': "Catégorie du colis",
  'add_booking.p_weight_field': "Poids du colis",
  'add_booking.p_size_field': "Taille",
  'add_booking.p_value_field': "Valeur déclarative du colis",
  'add_booking.proposed_price_field': "Prix Proposé",
  'add_booking.rec_name_field': "Prénom et Nom du destinataire final",
  'add_booking.rec_phone_number_field': "Numéro de téléphone du destinataire final",
  'add_booking.p_description_field': "Description du colis",
  'add_booking.terms_check': "J’ai lu et j’accepte les conditions générales",
  'add_booking.user_agreement_check': "J’ai lu et je m’engage à respecter les règles de bienveillance du site",
  'add_booking.back': "Précédent",
  'add_booking.next': "Suivant",
  'add_booking.confirm_request': "Confirmer",
  'add_booking_modal.add_request': "Ajouter un colis",
  'add_booking_modal.cancel': "Annuler",
  'signup.title': "Inscrivez-vous sur Inzula",
  'signup.f_name': "Prénom",
  'signup.l_name': "Nom",
  'signup.username': "Nom d'utilisateur",
  'signup.email': "E-mail",
  'signup.passport': "Mot de passe",
  'signup.confirm_password': "Confirmez le mot de passe",
  'signup.agree_terms': "J’ai lu et je m’engage à respecter les règles de bienveillance du site",
  'signup.signup': "Inscrivez-vous",
  'signup.have_account': "Vous avez déjà un compte?",
  'signup.login': "Se connecter",
  'signup.use_fb': " Continuer avec Facebook",
  'signup.use_gmail': " Continuer avec Gmail",
  'signup.use_email': "Utiliser mon adresse e-mail",
  'signup_discount.title': "Inscrivez-vous maintenant pour bénéficier d'une réduction de 5% sur chacune de vos trois premières épéditions de colis.",
  'transport_title.services_title': "Nous sommes fiers d'offrir ces services",
  'transport_title.add_trip': "Ajoutez votre trajet",
  'transport_title.make_offer': "FAIRE DES OFFRES DE TRANSPORT DE COLIS",
  'transport_title.meet_sender': "RENCONTRE AVEC L'EXPÉDITEUR - RECUPERER LE PAQUET",
  'transport_title.deliver': "LIVRER LE COLIS ET ÊTRE PAYÉ",
  'trip_card.username': "Nom: ",
  'trip_card.comeback_date': "Date de Retour: ",
  'trip_card.depart_date': "Date de Départ: ",
  'trip_card.departure_location': "Départ: ",
  'trip_card.destination_location': "Arrivée: ",
};
