# Generated by Django 2.2 on 2021-01-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_date', models.DateField()),
                ('comeback_date', models.DateField(blank=True, null=True)),
                ('proof', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('estimated_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('parcel_collection_point', models.CharField(blank=True, max_length=50, null=True)),
                ('accepted_parcel_types', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('trip_type', models.CharField(choices=[('round_trip', 'Round trip'), ('one_way_trip', 'One way trip')], max_length=50)),
            ],
        ),
    ]
