# Generated by Django 2.2 on 2020-10-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('proof', models.FileField(upload_to='uploads/')),
                ('estimated_amount', models.CharField(max_length=50)),
                ('parcel_collection_point', models.CharField(max_length=50)),
                ('accepted_parcel_types', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField()),
            ],
        ),
    ]
