# Generated by Django 2.2 on 2020-10-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20201029_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='comeback_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='depart_date',
            field=models.DateField(),
        ),
    ]
