# Generated by Django 2.2 on 2020-10-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20201014_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_type',
            field=models.CharField(choices=[('round_trip', 'Round trip'), ('one_way_trip', 'One way trip')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
