# Generated by Django 2.2 on 2021-01-11 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20201226_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='space_available',
        ),
    ]
