# Generated by Django 2.2 on 2021-11-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20210116_1807'),
        ('trip', '0002_auto_20210116_1802'),
    ]

    operations = [
    ]
