# Generated by Django 2.2 on 2020-10-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_auto_20201024_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='parcel_collection_point',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
