# Generated by Django 2.2 on 2020-10-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0007_auto_20201024_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='departure_location',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination_location',
            field=models.CharField(max_length=250),
        ),
    ]
